# Generated by Django 4.1.7 on 2023-02-25 12:22

from django.db import migrations, models

import chat_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chat_app.models.UserFile.file_upload_path,
                        verbose_name="ファイル",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="ユーザーネーム"),
        ),
    ]
