# Generated by Django 4.1.7 on 2023-03-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0003_userfile_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=240)),
                ("auth_code", models.CharField(max_length=6, verbose_name="認証コード")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日")),
            ],
        ),
    ]
